implement starknet-rs support for block endpoints
NethermindEth/rpc-request-builder pull request #21
Opened 2024-02-16 03:24 UTC by Prabhat1308

This PR implements the ```starknet-rs``` support for block endpoints. 
Fixes #14

2024-02-21 00:38 UTC, jelilat requested changes
Thank you for your contribution. I made some minor changes recommendation

2024-02-21 00:38 UTC, jelilat commented on src/api/rpcspec/methods.ts
> +      core::types::{BlockId, BlockTag,MaybePendingBlockWithTxHashes},
```suggestion
      core::types::{BlockId, BlockTag},
```

2024-02-21 00:38 UTC, jelilat commented on src/api/rpcspec/methods.ts
> +      core::types::{BlockId, BlockTag,MaybePendingBlockWithTxs},
```suggestion
      core::types::{BlockId, BlockTag},
```

2024-02-21 00:38 UTC, jelilat commented on src/api/rpcspec/methods.ts
> +    };
```suggestion
    starknetRs: `use starknet::providers::{
    jsonrpc::{HttpTransport, JsonRpcClient},
    Provider, Url,
};
```

2024-02-21 00:38 UTC, jelilat commented on src/api/rpcspec/methods.ts
> +  };
```suggestion
    starknetRs: `use starknet::{
    core::types::{BlockId, BlockTag},
    macros::felt,
    providers::{
        jsonrpc::{HttpTransport, JsonRpcClient},
        Provider, Url,
    },
};
```

2024-02-21 00:38 UTC, jelilat commented on src/components/constant.ts
> +  };
```suggestion
  };
  
```

2024-02-21 00:38 UTC, jelilat commented on src/api/rpcspec/methods.ts
> +    use starknet::providers::{
```suggestion
    starknetRs: `use starknet::providers::{
```

2024-02-21 00:38 UTC, jelilat commented on src/api/rpcspec/methods.ts
> +    use starknet::{
```suggestion
    starknetRs: `use starknet::{
```

2024-02-21 00:38 UTC, jelilat commented on src/api/rpcspec/methods.ts
> +    use starknet::{
```suggestion
    starknetRs: `use starknet::{
```

2024-02-21 00:38 UTC, jelilat commented on src/api/rpcspec/methods.ts
> +      use starknet::{
```suggestion
    starknetRs: `use starknet::{
```

2024-02-21 08:10 UTC, Prabhat1308 commented
@jelilat I have made the changes please review.

2024-02-22 06:53 UTC, jelilat approved these changes

2024-02-22 06:53 UTC, merged

2024-02-22 06:54 UTC, jelilat commented
Thank you for your contribution @Prabhat1308