(Feat): Implemented `Starknet.go` support for trace endpoints
NethermindEth/rpc-request-builder pull request #25
Opened 2024-02-17 12:14 UTC by Abhijay007

This PR implements the `starknet-go` support for the following RPC endpoints.

- `starknet_traceTransaction`
- `starknet_traceBlockTransactions`
- `starknet_simulateTransactions`

Fixes: #11

2024-02-23 00:36 UTC, jelilat requested changes
Kindly check [starknet.go](https://github.com/NethermindEth/starknet.go) to understand how these endpoints are implemented

2024-02-23 00:36 UTC, jelilat commented on src/api/rpcspec/methods.ts
> +    result, err := provider.getTransactionTrace(context.Background())
```suggestion
    transactionHash, _ := utils.HexToFelt("0x7641514f46a77013e80215cdce2e55d5aca49c13428b885c7ecb9d3ddb4ab11")
	result, err := provider.TraceTransaction(context.Background(), transactionHash)
```

2024-02-23 00:36 UTC, jelilat commented on src/components/Builder.tsx
>      const updateStarknetGoParams = (currentParamsObj: {
`updateStarknetGoParams` has now been implemeneted. Please rebase

2024-02-27 07:57 UTC, jelilat requested changes

2024-02-27 07:57 UTC, jelilat commented on src/components/Builder.tsx
remove the extra space you added

2024-02-27 07:57 UTC, jelilat commented on src/api/rpcspec/methods.ts
> +    result, err := provider.SimulateTransactions(context.Background(), rpc.BlockID{Tag: "latest"}, transactions, simulationFlags)
`transactions` and `simulation_flags` variables should be defined

2024-02-27 08:37 UTC, Abhijay007 commented on src/components/Builder.tsx
I attempted to remove this, but it appears that there is no extra space. Also, I tried fetching the changes from the upstream 'builder' file, but they are exactly the same. I am uncertain why this issue persists.

2025-09-04 06:14 UTC, closed without merging