Implements starknet.go Class RPC endpoints for builder
NethermindEth/rpc-request-builder pull request #27
Opened 2024-02-17 14:35 UTC by dhirajs0

support for starknet.go code for the following RPC endpoints

starknet_getClass
starknet_getClassHashAt
starknet_getClassAt

Closes #9

2024-02-23 00:29 UTC, jelilat requested changes
Please make the changes and resolve the conflicts and it should be GTM.

2024-02-23 00:29 UTC, jelilat commented on src/api/rpcspec/methods.ts
> +	rpcUrl := "https://free-rpc.nethermind.io/mainnet-juno/?apikey=GGfMLnf5icG5MM68u2mV8gXj83bx2uC9KowlL2yoKQSM71b3"
```suggestion
	rpcUrl := "https://free-rpc.nethermind.io/mainnet-juno/"
```

2024-02-23 00:29 UTC, jelilat commented on src/api/rpcspec/methods.ts
> +    fmt.Println("ClassOutput : ", result)
```suggestion
    fmt.Println("ClassOutput: ", result)
```

2024-02-23 00:29 UTC, jelilat commented on src/api/rpcspec/methods.ts
> +    fmt.Println("ClassHash is :", result)
```suggestion
    fmt.Println("ClassHash:", result)
```

2024-02-23 00:29 UTC, jelilat commented on src/api/rpcspec/methods.ts
> +    fmt.Println("ClassOutput : ", result)
```suggestion
    fmt.Println("ClassOutput: ", result)
```

2024-02-23 04:24 UTC, dhirajs0 commented
> Please make the changes and resolve the conflicts and it should be GTM.

Made the suggested changes.

2024-02-23 14:35 UTC, merged

2024-02-23 14:35 UTC, jelilat commented
Thank you for your contribution @dhirajs0

2024-03-06 11:09 UTC, AryanGodara commented
@jelilat I had a doubt in these implementations. Since this is an RPC builder, and the requests are editable.
<img width="1367" alt="image" src="https://github.com/NethermindEth/rpc-request-builder/assets/65490434/05f5b16c-f5c2-41ff-967b-9b4b5563d94c">
Initially, the code is correct, according to the fields like `latest` or `blockHash`.

But, as soon as I edit any input field, the code restructures, and is no longer correct. So, the `configuration of the request` isn't really working. I noticed this in most examples other than javascript, ie for Go and Rust
Eg.:
<img width="1384" alt="image" src="https://github.com/NethermindEth/rpc-request-builder/assets/65490434/2a782e64-dbdd-477d-b9a7-9e11222d876a">
After changing classHash, the `hextoFelt line disappears`
<img width="1408" alt="image" src="https://github.com/NethermindEth/rpc-request-builder/assets/65490434/b247bc76-3e1d-47e1-823d-63393e7c62a5">
after changing block number, the input parameter changes completely.

2024-03-06 12:04 UTC, jelilat commented
@AryanGodara This happens because the only acceptable block tag is "latest" or "pending". If you edit the block tag to pending, it should be properly updated. 

For example, this is what it looks like if I change the tag to "pending"

![Uploading Screenshot 2024-03-06 at 15.04.09.png…]()

2024-03-06 12:06 UTC, jelilat commented
@AryanGodara This happens because the only acceptable block tag is "latest" or "pending". If you edit the block tag to pending, it should be properly updated. 

For example, this is what it looks like if I change the tag to "pending"

<img width="1366" alt="Screenshot 2024-03-06 at 15 04 09" src="https://github.com/NethermindEth/rpc-request-builder/assets/23613565/9a911739-ae7f-42ad-9784-4899b5edc42c">